#!/usr/bin/env node
/**
 * adapters/codex.mjs -- canonical process -> codex-dialect prompt file (REQ-03).
 *
 * A PURE FUNCTION (ADR-0201), same contract as the claude-code adapter.
 *
 * THE HONEST NOTE THIS FILE OWES ITS READER. The design source claimed `.codex/` and
 * `AGENTS.md` already existed at the repo root and that adapters would "formalize what
 * these started". Verified at kickoff: they do NOT exist and never appear in git history.
 * So this adapter has **no prior art to conform to** — it is a target arc is inventing,
 * not a published format arc is matching. What it therefore aims at is the honest thing:
 * a runnable, self-describing prompt whose OUTPUT CONTRACT is identical to the
 * claude-code target's, because the design source's own framing is that drivers differ
 * and the output contract is the equalizer.
 *
 * `agent.invoke` is the known hard case (ADR-0206 leaves it deliberately coarse). Codex
 * has no subagent mechanism to translate it into, so rather than emit something that
 * superficially resembles a working delegation, this adapter renders it as an explicit
 * inline instruction and records the limitation in the file itself. Silently degrading it
 * would make REQ-03 pass mechanically while failing its intent.
 */

export const TOOL_MAP = Object.freeze({
  "git.op": { kind: "scoped", render: (scope) => `git ${scope}` },
  "shell.run": { kind: "scoped", render: (scope) => scope },
  "fs.read": { kind: "bare", token: "read files" },
  "fs.write": { kind: "bare", token: "write files" },
  "agent.invoke": { kind: "bare", token: null }, // handled explicitly below
  "web.search": { kind: "bare", token: "search the web" },
  "ask.human": { kind: "bare", token: "ask the operator" },
});

/** Placeholders in codex dialect: named `${NAME}` with shell-style defaults. */
export function renderPlaceholders(body, inputs) {
  const list = Array.isArray(inputs) ? inputs : [];
  return body.replace(/\{\{input\.([a-z][a-z0-9_-]*)(?:\|default:([^}]*))?\}\}/g, (whole, name, dflt) => {
    if (!list.some((i) => i.name === name)) throw new Error(`codex adapter: placeholder names undeclared input \`${name}\``);
    return dflt !== undefined ? `\${${name.toUpperCase()}:-${dflt}}` : `\${${name.toUpperCase()}}`;
  });
}

export function render(doc) {
  const lines = [
    `# ${doc.name}`,
    "",
    "<!-- GENERATED by arc-compile --target codex. DO NOT EDIT.",
    `     Source of truth: processes/${doc.name}.process.yaml (v${doc.version})`,
    "     Regenerate: node .claude/scripts/engine/arc-compile.mjs --write --all --target codex -->",
    "",
    `**Intent:** ${doc.intent}`,
    "",
  ];

  const inputs = Array.isArray(doc.inputs) ? doc.inputs : [];
  if (inputs.length) {
    lines.push("**Inputs:**", "");
    for (const i of inputs) {
      const d = "default" in i ? ` (default \`${i.default}\`)` : i.required ? " (required)" : "";
      lines.push(`- \`${i.name.toUpperCase()}\` — ${i.description}${d}`);
    }
    lines.push("");
  }

  const grants = [];
  let delegates = false;
  for (const t of doc.tools ?? []) {
    const bare = typeof t === "string";
    const prim = bare ? t : Object.keys(t)[0];
    const spec = TOOL_MAP[prim];
    if (!spec) throw new Error(`codex adapter: no mapping for abstract tool \`${prim}\``);
    if (prim === "agent.invoke") { delegates = true; continue; }
    // This dialect states grants in prose; a path-scoped write would reach codex as "write files", everywhere. Refused,
    // never widened -- only claude-code renders the paths as Edit(<path>) grants (attack 1be4183 B6).
    if (prim === "fs.write" && !bare) throw new Error("codex adapter: fs.write is declared with paths, and this dialect cannot fence a path -- run this process on claude-code");
    if (spec.kind === "bare") { if (spec.token) grants.push(spec.token); continue; }
    if (bare) { grants.push(`run ${prim === "git.op" ? "git" : "shell"} commands`); continue; }
    for (const scope of t[prim]) grants.push(`\`${spec.render(scope)}\``);
  }
  if (grants.length) {
    lines.push(`**This process may:** ${grants.join(", ")}.`, "");
  }
  if (delegates) {
    // Stated, not hidden. ADR-0206 predicted this exact gap for `arc-kickoff`.
    lines.push(
      "> **Delegation note.** This process declares `agent.invoke`, which has no direct",
      "> equivalent on this target. Perform the delegated work inline, in this same",
      "> session, and hold yourself to the same contract the delegated role would carry.",
      "",
    );
  }

  lines.push("---", "", renderPlaceholders(doc.body, doc.inputs).replace(/\n+$/, ""), "");
  return lines.join("\n");
}

// ---------- source input: commands and agents (distribute P03, ADR-2017/2018) ----------
//
// Verified against Codex 0.147.0 (matrix row `codex`): there are no project slash commands, so a command
// renders as the skill `.agents/skills/NAME/SKILL.md` (invoked `$NAME`), and an agent renders as
// `.codex/agents/NAME.toml` carrying `developer_instructions`. Codex has no per-skill or per-agent tool
// allowlist, so the fence drops under the `partial` cell and the install's degraded lines name it.

import { Unsupported, fate, markdown, plainValue, yamlScalar } from "./source-common.mjs";

/** A TOML basic string: JSON's escapes are TOML's, plus DEL, which TOML forbids unescaped. */
export const tomlString = (s) => JSON.stringify(s).replace(/\x7f/g, "\u007f");

/** A TOML multi-line literal string when the body allows one, else a basic string, so no escape is read. */
export function tomlBlock(body) {
  if (!body.includes("'''") && !/[\x00-\x08\x0b-\x1f\x7f]/.test(body.replace(/\r\n/g, "\n"))) return `'''\n${body}'''`;
  return tomlString(body);
}

export function renderSourceFiles(unit) {
  const dropped = [];
  for (const key of Object.keys(unit.fields)) {
    const f = fate(unit, key, "codex");
    if (f.startsWith("drop:")) dropped.push(`${key} (${f.slice(5)})`);
  }
  if (!("description" in unit.fields)) throw new Unsupported("no `description`, which every Codex skill and agent needs");
  if (unit.kind === "commands") {
    const front = [`name: ${unit.stem}`, `description: ${yamlScalar(unit.fields.description)}`];
    return { files: [{ path: `.agents/skills/${unit.stem}/SKILL.md`, text: markdown(front, "codex", unit.body) }], dropped };
  }
  const text = [
    "# GENERATED by arc-compile --target codex --input source from .claude/. DO NOT EDIT: change the source and re-run.",
    `name = ${tomlString(unit.stem)}`,
    `description = ${tomlString(plainValue(unit.fields.description))}`,
    `developer_instructions = ${tomlBlock(unit.body.replace(/^\n+/, ""))}`,
    "",
  ].join("\n");
  return { files: [{ path: `.codex/agents/${unit.stem}.toml`, text }], dropped };
}
