#!/usr/bin/env node
/**
 * adapters/source-common.mjs -- what every non-claude source render shares (distribute P03, ADR-2018).
 *
 * A source unit is one parsed command or agent file. Each target adapter's `renderSourceFiles(unit)`
 * returns the files it writes for that unit, or throws `Unsupported` with the reason, so arc-compile
 * prints `[unsupported] <file> — <reason>` and never writes something that only resembles the source
 * (ADR-2001: no prose fallback). The fate of every key comes from engine/frontmatter-keys.yaml, read
 * once by arc-compile and handed in as `unit.fates`, so an adapter cannot invent a fate the table and
 * frontmatter-lint never saw.
 */

export class Unsupported extends Error {}

// The agentskills name grammar, which Codex and OpenCode skills share: lowercase words joined by
// single hyphens, 64 characters at most. A stem outside it is refused rather than slugged, because a
// slug can collide with another file's stem and silently overwrite it.
const NAME = /^[a-z0-9]+(-[a-z0-9]+)*$/;

/** One parsed source file as a unit: kind, stem, frontmatter fields by key, body, and the key fates. */
export function sourceUnit(parsed, kind, rel, fates) {
  const base = rel.split("/").slice(2).join("/");
  if (base.includes("/")) throw new Unsupported(`a nested ${kind} file has no flat name on this target`);
  const stem = base.replace(/\.md$/, "");
  if (stem.length > 64 || !NAME.test(stem)) throw new Unsupported(`the name \`${stem}\` is outside the skill-name grammar (lowercase words joined by single hyphens, 64 characters at most)`);
  const fields = Object.create(null);
  for (const l of parsed.lines) fields[l.key] = l.raw;
  return { kind, stem, rel, fields, body: parsed.rest, fates };
}

/** The fate of `key` on `target`, as the table spells it. A key with no row is frontmatter-lint's failure. */
export function fate(unit, key, target) {
  const f = unit.fates?.[unit.kind]?.[key]?.[target];
  if (typeof f !== "string") throw new Unsupported(`no fate for \`${key}\` on \`${target}\` in engine/frontmatter-keys.yaml`);
  if (f === "unsupported") throw new Unsupported(`\`${key}\` is declared unsupported on \`${target}\``);
  return f;
}

/**
 * The frontmatter value as a YAML scalar. A value the source already quotes is kept as written; any
 * other is emitted as a JSON string, which is a valid YAML double-quoted scalar, so a colon, a `#` or
 * a leading `[` in a description cannot change what a strict YAML reader sees (Claude Code reads the
 * raw line and never had to care).
 */
export function yamlScalar(raw) {
  if (/^"(?:[^"\\]|\\.)*"$/.test(raw) || /^'(?:[^']|'')*'$/.test(raw)) return raw;
  return JSON.stringify(raw);
}

/** The value with one layer of YAML quoting removed, for a target that is not YAML (TOML). */
export function plainValue(raw) {
  if (/^"(?:[^"\\]|\\.)*"$/.test(raw)) { try { return JSON.parse(raw); } catch { throw new Unsupported(`the value ${raw} is a double-quoted string JSON cannot read`); } }
  if (/^'(?:[^']|'')*'$/.test(raw)) return raw.slice(1, -1).replace(/''/g, "'");
  return raw;
}

/** A Claude tool list (`Bash(git diff:*), Read`) split on its top-level commas only. */
export function splitTools(raw) {
  const out = [];
  let depth = 0, cur = "";
  for (const ch of plainValue(raw)) {
    if (ch === "(") depth++;
    if (ch === ")") { depth--; if (depth < 0) throw new Unsupported(`the tool list ${raw} has an unbalanced \`)\``); }
    if (ch === "," && depth === 0) { out.push(cur.trim()); cur = ""; continue; }
    cur += ch;
  }
  if (depth !== 0) throw new Unsupported(`the tool list ${raw} has an unbalanced \`(\``);
  out.push(cur.trim());
  if (out.some((t) => t === "")) throw new Unsupported(`the tool list ${raw} has an empty entry`);
  return out;
}

/** The targets a unit renders for: its `targets:` list, or every verified row when it has none. */
export function targetsOf(unit, rows) {
  if (!("targets" in unit.fields)) return rows;
  return plainValue(unit.fields.targets).split(",").map((s) => s.trim());
}

export const banner = (target) =>
  `<!-- GENERATED by arc-compile --target ${target} --input source from .claude/. DO NOT EDIT: change the source and re-run. -->`;

/** A markdown file: frontmatter lines, the banner, then the source body unchanged. */
export function markdown(front, target, body) {
  return `---\n${front.map((l) => `${l}\n`).join("")}---\n${banner(target)}${body}`;
}
