#!/usr/bin/env bats
# docs Phase 02 -- the renderer (REQ-01, REQ-04, REQ-06, REQ-08; ADR-1504..1506, ADR-1510).
#
# wiki.json -> docs/wiki/**: one page per entity plus an index, every generated file carrying the
# do-not-edit banner, narrative included verbatim from docs/wiki/_narrative/ or a visible
# "narrative pending" banner in its place. CI proves the committed pages are exactly what the
# renderer writes -- twice, by --check and by an independent render diffed with diff -r -- and
# the mutants prove both checks can fail.
#
# Every test asserts that the thing it checks RAN before asserting what it printed.
bats_require_minimum_version 1.5.0
load 'test_helper'

WB() { printf '%s' "$1/.claude/scripts/docs/wiki-build.mjs"; }
COV() { printf '%s' "$1/.claude/scripts/docs/wiki-coverage.mjs"; }
BANNER='<!-- GENERATED by .claude/scripts/docs/wiki-build.mjs'

# a scratch arc tree (one of every entity), rendered; prints its root
rendered_tree() {
  local d="$BATS_TEST_TMPDIR/tree-$1"
  node "$ARC_ROOT/tests/docs/fixture-tree.mjs" "$ARC_ROOT" "$d" >/dev/null || return 1
  node "$(WB "$d")" --root "$d" >/dev/null || return 1
  [ -s "$d/docs/wiki/index.md" ] || return 1
  printf '%s' "$d"
}

@test "docs-render: REQ-06 -- the committed docs/wiki is exactly what the renderer writes (--check)" {
  [ -s "$ARC_ROOT/docs/wiki/index.md" ] || { echo "docs/wiki/index.md is not committed"; false; }
  run node "$(WB "$ARC_ROOT")" --check
  [[ "$output" == "wiki-build: check "* ]] || { echo "the check did not run: $output"; false; }
  [ "$status" -eq 0 ] || { echo "$output"; false; }
}

@test "docs-render: REQ-06 -- an independent render into scratch, diffed with diff -r, is identical" {
  local s="$BATS_TEST_TMPDIR/scratch-wiki"
  run node "$(WB "$ARC_ROOT")" --out "$s"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  [ -s "$s/index.md" ] || { echo "nothing rendered: $output"; false; }
  run diff -r --exclude=_narrative "$ARC_ROOT/docs/wiki" "$s"
  [ "$status" -eq 0 ] || { echo "the committed wiki differs from a fresh render:"; echo "$output" | head -40; false; }
}

@test "docs-render: REQ-06 mutants -- a one-byte edit, a deleted page and a stale page each turn --check RED by name" {
  local t; t=$(rendered_tree mut) || { echo "fixture failed"; false; }
  run node "$(WB "$t")" --root "$t" --check
  [ "$status" -eq 0 ] || { echo "clean fixture not clean: $output"; false; }
  # one byte
  printf ' ' >> "$t/docs/wiki/products/alpha.md"
  run node "$(WB "$t")" --root "$t" --check
  [ "$status" -eq 1 ] || { echo "one-byte edit survived (status $status): $output"; false; }
  [[ "$output" == *"docs/wiki/products/alpha.md"* ]] || { echo "edited page not named: $output"; false; }
  [[ "${lines[0]}" == *"node .claude/scripts/docs/wiki-build.mjs"* ]] || { echo "first line does not name the fix: ${lines[0]}"; false; }
  # deleted page
  node "$(WB "$t")" --root "$t" >/dev/null
  rm "$t/docs/wiki/lanes/alpha.md"
  run node "$(WB "$t")" --root "$t" --check
  [ "$status" -eq 1 ] || { echo "deleted page survived: $output"; false; }
  [[ "$output" == *"docs/wiki/lanes/alpha.md"* ]] || { echo "deleted page not named: $output"; false; }
  # stale generated page (a banner-carrying page for nothing)
  node "$(WB "$t")" --root "$t" >/dev/null
  printf '%s -- DO NOT EDIT. -->\n# ghost\n' "$BANNER" > "$t/docs/wiki/products/ghost.md"
  run node "$(WB "$t")" --root "$t" --check
  [ "$status" -eq 1 ] || { echo "stale page survived: $output"; false; }
  [[ "$output" == *"docs/wiki/products/ghost.md"* ]] || { echo "stale page not named: $output"; false; }
}

@test "docs-render: rendering removes a stale GENERATED page and never touches a hand-written file" {
  local t; t=$(rendered_tree stale) || { echo "fixture failed"; false; }
  printf '%s -- DO NOT EDIT. -->\n# ghost\n' "$BANNER" > "$t/docs/wiki/products/ghost.md"
  printf 'hand-written, no banner\n' > "$t/docs/wiki/products/hand.md"
  local before; before=$(cksum < "$t/docs/wiki/products/hand.md")
  run node "$(WB "$t")" --root "$t"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  [ ! -e "$t/docs/wiki/products/ghost.md" ] || { echo "the stale generated page was left behind"; false; }
  [ "$(cksum < "$t/docs/wiki/products/hand.md")" = "$before" ] || { echo "a hand-written file was changed"; false; }
}

@test "docs-render: REQ-01 -- wiki-coverage passes on the real tree, counts equal to wiki.json" {
  run node "$(WB "$ARC_ROOT")" --json --out "$BATS_TEST_TMPDIR/w.json"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  local n
  n=$(node -e 'const e=JSON.parse(require("fs").readFileSync(process.argv[1],"utf8")).entities;console.log(Object.values(e).reduce((a,l)=>a+l.length,0))' "$BATS_TEST_TMPDIR/w.json")
  [ "$n" -gt 100 ] || { echo "implausible entity count $n"; false; }
  run node "$(COV "$ARC_ROOT")"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  [[ "$output" == *"wiki-coverage: $n entities, $n pages, "*" -- all covered"* ]] || { echo "counts are not wiki.json's $n: $output"; false; }
}

@test "docs-render: REQ-04 -- a manifest-only product appears with its facts and the pending banner" {
  local t; t=$(rendered_tree req04) || { echo "fixture failed"; false; }
  mkdir -p "$t/products/zeta"
  printf '{"name":"zeta","version":"9.8.7","requires":["core"],"commands":[],"agents":[],"scripts":[],"files":[],"docs":[]}\n' > "$t/products/zeta/manifest.json"
  run node "$(WB "$t")" --root "$t"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  local p="$t/docs/wiki/products/zeta.md"
  [ -s "$p" ] || { echo "no page for zeta"; false; }
  run cat "$p"
  [[ "${lines[0]}" == "$BANNER"* ]] || { echo "line 1 is not the banner: ${lines[0]}"; false; }
  [[ "$output" == *"# zeta"* ]] || { echo "no title: $output"; false; }
  [[ "$output" == *"9.8.7"* ]] || { echo "version missing: $output"; false; }
  [[ "$output" == *"[core](core.md)"* ]] || { echo "requires not linked: $output"; false; }
  [[ "$output" == *"Narrative pending."* ]] || { echo "no pending banner: $output"; false; }
  run node "$(COV "$t")" --root "$t"
  [ "$status" -eq 0 ] || { echo "the new product is not covered: $output"; false; }
}

@test "docs-render: a narrative is included verbatim, replaces the pending banner, and is never rewritten" {
  local t; t=$(rendered_tree narr) || { echo "fixture failed"; false; }
  mkdir -p "$t/docs/wiki/_narrative/products"
  printf 'Alpha exists because the fixture needs one of everything.\n' > "$t/docs/wiki/_narrative/products/alpha.md"
  local before; before=$(cksum < "$t/docs/wiki/_narrative/products/alpha.md")
  run node "$(WB "$t")" --root "$t"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  run cat "$t/docs/wiki/products/alpha.md"
  [[ "$output" == *"Alpha exists because the fixture needs one of everything."* ]] || { echo "narrative not included: $output"; false; }
  if [[ "$output" == *"Narrative pending."* ]]; then echo "pending banner shown beside a narrative: $output"; false; fi
  [ "$(cksum < "$t/docs/wiki/_narrative/products/alpha.md")" = "$before" ] || { echo "the narrative file was rewritten"; false; }
}

@test "docs-render: every generated file carries the banner, no CR, no checkout path" {
  run node "$ARC_ROOT/tests/docs/tree-hygiene.mjs" "$ARC_ROOT/docs/wiki" "$ARC_ROOT" --banner-prefix "$BANNER"
  [[ "$output" == "tree-hygiene: checked "[1-9]* ]] || { echo "hygiene did not run: $output"; false; }
  [ "$status" -eq 0 ] || { echo "$output"; false; }
}

@test "docs-render: two renders are byte-identical" {
  run node "$(WB "$ARC_ROOT")" --out "$BATS_TEST_TMPDIR/r1"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  run node "$(WB "$ARC_ROOT")" --out "$BATS_TEST_TMPDIR/r2"
  [ "$status" -eq 0 ] || { echo "$output"; false; }
  [ -s "$BATS_TEST_TMPDIR/r1/index.md" ] || { echo "first render wrote nothing"; false; }
  run diff -r "$BATS_TEST_TMPDIR/r1" "$BATS_TEST_TMPDIR/r2"
  [ "$status" -eq 0 ] || { echo "$output" | head -20; false; }
}

@test "docs-render: every relative link in every generated page resolves" {
  run node "$ARC_ROOT/tests/docs/link-check.mjs" "$ARC_ROOT/docs/wiki"
  [[ "$output" == "link-check: "[1-9]*" page(s), "[1-9]*" link(s) checked"* ]] || { echo "link check did not run: $output"; false; }
  [ "$status" -eq 0 ] || { echo "$output" | head -40; false; }
}

@test "docs-render: the link checker itself goes red on a broken link and a missing heading" {
  local t; t=$(rendered_tree links) || { echo "fixture failed"; false; }
  printf '[x](nowhere.md) [y](index.md#no-such-heading)\n' >> "$t/docs/wiki/products/alpha.md"
  run node "$ARC_ROOT/tests/docs/link-check.mjs" "$t/docs/wiki"
  [ "$status" -eq 1 ] || { echo "status $status: $output"; false; }
  [[ "$output" == *"BROKEN products/alpha.md -> nowhere.md (no such file)"* ]] || { echo "file link not named: $output"; false; }
  [[ "$output" == *"BROKEN products/alpha.md -> index.md#no-such-heading (no such heading)"* ]] || { echo "anchor not named: $output"; false; }
}

@test "docs-render: REQ-08 -- the four overlapping documents are short stubs into the wiki, with archived copies" {
  local name
  for name in how-it-works how-arc-works-simple usermanual blueprint; do
    local stub="$ARC_ROOT/docs/$name.md" arch="$ARC_ROOT/docs/archive/$name.md"
    [ -s "$stub" ] || { echo "$name: the stub is missing"; false; }
    [ "$(wc -l < "$stub" | tr -d ' ')" -le 10 ] || { echo "$name: stub longer than 10 lines"; false; }
    grep -q "wiki/index.md" "$stub" || { echo "$name: stub does not point into the wiki"; false; }
    grep -q "archive/$name.md" "$stub" || { echo "$name: stub does not name its archive copy"; false; }
    [ "$(wc -l < "$arch" | tr -d ' ')" -gt 100 ] || { echo "$name: archive copy missing or not the full document"; false; }
    grep -q "docs/archive/$name.md" "$ARC_ROOT/docs/strategy/README.md" || { echo "$name: the strategy file map does not record the move"; false; }
  done
}

@test "docs-render: the CLI refuses --check with --json, --out in the tree outside docs/wiki, and unknown flags" {
  run node "$(WB "$ARC_ROOT")" --check --json
  [ "$status" -eq 2 ] || { echo "--check --json: status $status: $output"; false; }
  run node "$(WB "$ARC_ROOT")" --out "$ARC_ROOT/products"
  [ "$status" -eq 2 ] || { echo "--out into the tree: status $status: $output"; false; }
  run node "$(WB "$ARC_ROOT")" --render
  [ "$status" -eq 2 ] || { echo "unknown flag: status $status: $output"; false; }
}

@test "docs-render: this suite registers exactly the tests it declares" {
  [ "${#BATS_TEST_NAMES[@]}" -eq 14 ] || { echo "registered ${#BATS_TEST_NAMES[@]}, declared 14"; false; }
}
