#!/usr/bin/env node
/**
 * process-lint.mjs -- the gate on the canonical process layer (Phase 00).
 *
 * Every check is STRUCTURAL: a presence-or-parse question with no judgement in it, so every
 * one exits 1. On the WARN-first question -- which the PLAN's no-go and this phase's spec
 * could otherwise be read as contradicting -- the no-go governs promoting a gate to BLOCK
 * *in the CI pipeline*, which this phase does not do. It does not govern the tool's own exit
 * code: a lint that cannot exit non-zero on a hostile input is not a lint, and its fixtures
 * could assert nothing.
 *
 * REBUILT after the mandatory fresh-agent adversarial pass (phase-00-spec). Two unanchored
 * agents that had never seen the implementation found 22 real holes in a gate whose own 36
 * author-written fixtures all passed on the first run -- which is precisely what retro-log
 * 2026-08-02 says a clean author result means. The classes that mattered:
 *
 *   - `__proto__` as a key silently disabled THREE gates at once (see yaml-subset.mjs).
 *   - Five keyword/type combinations linted clean and enforced nothing, making this file's
 *     "no constraint is silently unenforced" promise false (see schema-subset.mjs).
 *   - The passthrough check matched a NAMING CONVENTION, not passthrough: `claude-code:`,
 *     `x_claude:` and any unknown key sailed through. Now the top-level key set is a
 *     WHITELIST, which subsumes the convention check, and the whole document is walked.
 *   - Dialect placeholders entered through `inputs[].default` and tool scopes, which the
 *     body-only scan never looked at.
 *   - `baseline` proved only "some file has this hash", never "the file this process is
 *     canonical for" -- and the body was entirely unchecked, so a body rewritten to say
 *     `git push --force` passed with a freshly-recomputed, fully green pin.
 *   - The block scalar was lossy (whitespace-only lines, trailing-newline count, `|+`
 *     accepted-and-ignored), so the round-trip was green by luck of today's content.
 *
 * Usage: process-lint.mjs [FILE...] | --all [--root PATH]
 * Zero dependencies, Node 18+.
 */

import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, realpathSync, statSync } from "node:fs";
import { join, relative, resolve, sep } from "node:path";

import { encodeBlockScalar, parseYamlSubset } from "./yaml-subset.mjs";
// Imported, not re-spelled. The header assertion used to be the hardcoded substring
// "GENERATED by arc-compile" -- unanchored, and containing neither the words DO NOT EDIT
// nor anything tying it to what the adapter actually emits. Two consequences, both real:
// the warning could be deleted from all three files with nothing red, and the FIRST edit to
// the header's wording broke the lint (it did, on the very next change). Asserting the
// adapter's own output makes the two impossible to drift apart.
import { renderHeader as renderClaudeCodeHeader } from "./adapters/claude-code.mjs";
import { KEYWORDS, validateSchemaDoc } from "./schema-subset.mjs";
// Imported, never copied: a regex copied out of the spine is a regex that drifts from the
// spine (retro-log 2026-07-22, counts that rot the moment the code moves).
import { PROCESS_RE } from "../hq/lib/validate.mjs";

// ADR-0206: seven primitives, capped. An eighth value is a FAIL, not an extension.
export const TOOLS = Object.freeze([
  "fs.read", "fs.write", "shell.run", "web.search", "git.op", "ask.human", "agent.invoke",
]);
export const PERMISSIONS = Object.freeze(["declared", "unrestricted"]);
// ADR-0206: the filter set is closed at ONE.
export const FILTERS = Object.freeze(["default"]);
export const TARGETS = Object.freeze(["claude-code", "codex"]);

// The whole top-level vocabulary. A WHITELIST rather than a pattern: the previous
// `x-<target>-*` regex enforced a naming convention, so any escape hatch that simply
// declined to use that spelling was invisible.
export const TOP_LEVEL_KEYS = Object.freeze([
  "name", "version", "intent", "permissions", "inputs", "tools", "output", "evals", "baseline", "body",
  // `job_stub` marks a SCHEDULED-JOB STUB rather than an engine process (scheduler ADR-0802).
  // ADR-0504 closes the policy subject set to `process:NAME` where NAME is a real stem in
  // processes/, so a scheduled job that must be authorized at all needs a file here -- and a
  // file here that is not an engine process needs to say so, or every engine gate reads it as
  // a broken process. See JOB_STUB_KEYS for the closed schema that replaces this one.
  "job_stub",
]);

/**
 * A job stub is its own document class, with its own CLOSED key set.
 *
 * It declares no engine contract, so `output`, `evals` and `baseline` are not merely optional
 * here -- they are FORBIDDEN. Carrying one would be a claim to be compiled, run and byte-diffed
 * against a live command, and the compiler deliberately never sees these files.
 */
export const JOB_STUB_KEYS = Object.freeze([
  "name", "version", "intent", "permissions", "inputs", "tools", "job_stub", "body",
]);
const INPUT_KEYS = Object.freeze(["name", "type", "required", "default", "description"]);
// `migrated` is optional and marks THE FLIP (ADR-0202). Before it, `baseline` is a live
// gate: the pinned hash is recomputed and the canonical body is compared against the live
// file's prose. After it, the byte-diff has retired and `baseline` is HISTORICAL
// provenance -- what this process was migrated from, and when. Comparing it live past the
// flip would fail forever, because the generated file now carries a DO-NOT-EDIT header the
// 7abeda1 pin predates. What replaces it is not nothing: `arc-compile --check` becomes the
// ongoing gate, which is also ADR-0201's hand-edit detection.
// `retired` (ADR-0207) marks the moment the file first legitimately changed, after which the
// proof no longer claims to reproduce the pre-flip command -- and that claim being false is the
// point, not a defect. Both baseline gates skip a retired file and count it apart.
const BASELINE_KEYS = Object.freeze(["target", "path", "commit", "sha256", "migrated", "retired"]);
const BASELINE_REQUIRED = Object.freeze(["target", "path", "commit", "sha256"]);

// Which live file each PILOT process is canonical for. Without this binding, `baseline`
// proved only that SOME file in the repo carries the pinned hash -- swapping the path to a
// different command (or to README.md) and recomputing the hash passed clean.
export const CANONICAL_BASELINE = Object.freeze({
  "commit-msg-draft": ".claude/commands/arc-commit.md",
  "review-diff": ".claude/commands/arc-review.md",
  "kickoff-plan": ".claude/commands/arc-kickoff.md",
});

// Exported so the test suite can assert every INDEX row names a REAL check id, rather than
// trusting a free-text column that could quietly neutralise a fixture.
export const CHECKS = Object.freeze([
  "yaml-parse", "yaml-excluded", "schema-keyword", "schema-shape", "name-semver",
  "tool-unknown", "permissions-invalid", "placeholder-dialect", "placeholder-malformed",
  "evals-path", "target-passthrough", "unknown-key", "baseline-drift", "body-drift", "frontmatter-injection",
  "body-unrepresentable", "inputs-shape", "intent-missing", "router-tier",
]);

const DIALECT_RES = [/\$\{\d+(:-[^}]*)?\}/g, /\$ARGUMENTS\b/g, /(^|[^\\$])\$\d\b/g];

// ---------- output ----------
const findings = [];
const add = (check, where, what, expected, found, example) =>
  findings.push({ check, where, what, expected, found, example });

function gitToplevel() {
  try {
    return execFileSync("git", ["rev-parse", "--show-toplevel"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] }).trim();
  } catch { return ""; }
}

const argv = process.argv.slice(2);
let root = "";
const files = [];
let all = false;
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a === "--all") all = true;
  else if (a === "--root") root = argv[++i] ?? "";
  else if (a.startsWith("--")) {
    console.error(`process-lint: unknown option ${a}`);
    process.exit(2);
  } else files.push(a);
}
root = resolve(root || gitToplevel() || ".");

if (all) {
  const dir = join(root, "processes");
  if (!existsSync(dir)) {
    console.error(`process-lint: no processes/ directory under ${root}`);
    process.exit(1);
  }
  for (const f of readdirSync(dir).sort()) if (f.endsWith(".process.yaml")) files.push(join(dir, f));
}
if (!files.length) {
  console.error("usage: process-lint.mjs [FILE...] | --all [--root PATH]");
  process.exit(2);
}

// ---------- helpers ----------
const sha256 = (s) => createHash("sha256").update(s).digest("hex");
const lf = (s) => s.replace(/\r\n/g, "\n").replace(/\r/g, "\n");
const short = (s, n = 60) => (String(s).length > n ? `${String(s).slice(0, n - 3)}...` : String(s));
const lineOf = (text, needle) => {
  const i = text.indexOf(needle);
  return i < 0 ? 1 : text.slice(0, i).split("\n").length;
};

/** Every (path, value) string pair in the document, so no check is body-only by accident. */
function* walkStrings(node, path = "") {
  if (typeof node === "string") { yield [path, node]; return; }
  if (Array.isArray(node)) { for (let i = 0; i < node.length; i++) yield* walkStrings(node[i], `${path}[${i}]`); return; }
  if (node && typeof node === "object") {
    for (const k of Object.keys(node)) {
      yield [`${path ? `${path}.` : ""}${k}`, k, "KEY"];
      yield* walkStrings(node[k], `${path ? `${path}.` : ""}${k}`);
    }
  }
}

/** Placeholders, parsed as a real pipeline so filter 2..n cannot hide behind filter 1. */
function checkPlaceholders(body, where, declared) {
  for (const m of body.matchAll(/\{\{([^{}]*)\}\}/g)) {
    const inner = m[1];
    const whole = `{{${inner}}}`;
    const segs = inner.split("|");
    const pathPart = segs[0];
    const pm = pathPart.match(/^input\.([a-z][a-z0-9_-]*)$/);
    if (!pm) {
      add("placeholder-malformed", where, `malformed placeholder \`${short(whole, 40)}\``,
        "{{input.NAME}} or {{input.NAME|default:VALUE}} — root is always `input`, exactly one level deep",
        whole, "{{input.base|default:main}}");
      continue;
    }
    if (declared && !declared.has(pm[1])) {
      add("placeholder-malformed", where, `placeholder names input \`${pm[1]}\`, which \`inputs:\` does not declare`,
        `one of: ${[...declared].join(", ") || "(none declared)"}`, pm[1], "declare it under inputs:, or fix the name");
    }
    // Every segment past the path is a filter. The old regex ended in `(.*)`, which swallowed
    // `|shellquote` into the DEFAULT VALUE -- so "the filter set is closed at one" was
    // unenforced for every filter after the first.
    for (let i = 1; i < segs.length; i++) {
      const fm = segs[i].match(/^([a-z]+):(.*)$/);
      if (!fm) {
        add("placeholder-malformed", where, `placeholder filter \`${short(segs[i], 20)}\` is not \`name:value\``,
          "default:VALUE", segs[i], "{{input.base|default:main}}");
        continue;
      }
      if (!FILTERS.includes(fm[1])) {
        add("placeholder-malformed", where, `unknown placeholder filter \`${fm[1]}\``,
          `the filter set is closed at: ${FILTERS.join(", ")}`, fm[1], "{{input.base|default:main}}");
      }
      if (i > 1) {
        add("placeholder-malformed", where, "chained placeholder filters are not supported",
          "exactly one filter", inner, "{{input.base|default:main}}");
      }
    }
  }
  // After removing every WELL-FORMED placeholder, no brace pair may remain. The old
  // balance-counter passed `{{input.nope}x}}` (1 open, 1 close, and the match regex could
  // not see it) and `}}text{{`.
  const residue = body.replace(/\{\{[^{}]*\}\}/g, "");
  for (const tok of ["{{", "}}"]) {
    if (residue.includes(tok)) {
      const n = body.slice(0, body.indexOf(tok)).split("\n").length;
      add("placeholder-malformed", where, `stray \`${tok}\` outside any well-formed placeholder (near body line ${n})`,
        "every {{ closed by a matching }} with nothing odd between",
        tok, "{{input.base}}");
      break;
    }
  }
}

// ---------- per-file checks ----------
for (const file of files) {
  const rel = relative(root, resolve(file)) || file;
  const at = (n) => `${rel}:${n}`;
  try {
    if (!existsSync(file)) {
      add("yaml-parse", at(1), "file does not exist", "a readable file", file, "check the path");
      continue;
    }
    const text = readFileSync(file, "utf8");

    const parsed = parseYamlSubset(text);
    if (!parsed.ok) {
      const e = parsed.error;
      add(e.check, at(e.line), e.what, e.expected, e.found, e.example);
      continue;
    }
    const doc = parsed.value;
    if (!doc || typeof doc !== "object" || Array.isArray(doc)) {
      add("yaml-parse", at(1), "root of the document is not a mapping", "a mapping", String(doc), "name: my-process");
      continue;
    }

    // --- unknown-key / target-passthrough: a WHITELIST, walked at every depth ---
    for (const k of Object.keys(doc)) {
      if (TOP_LEVEL_KEYS.includes(k)) continue;
      const isX = /^x[-_.]/i.test(k);
      add(isX ? "target-passthrough" : "unknown-key", at(lineOf(text, k)),
        isX ? `per-target passthrough key \`${k}\` is forbidden (ADR-0205)` : `unknown top-level key \`${k}\``,
        `one of: ${TOP_LEVEL_KEYS.join(", ")}`, k,
        "move the content into `body:`, or accept the residue as a named finding");
    }
    for (const [path, val, isKey] of walkStrings(doc)) {
      if (isKey === "KEY" && /(^|\.)x[-_.]/i.test(path)) {
        add("target-passthrough", at(lineOf(text, val)),
          `nested per-target passthrough key \`${path}\` is forbidden (ADR-0205)`,
          "no per-target keys at any depth", path, "move the content into `body:`");
      }
    }

    // --- a job stub is a different document class, and its checks END HERE (ADR-0802) ---
    //
    // It exists only so a scheduled job has a policy SUBJECT: ADR-0504 closes that set to
    // `process:NAME` where NAME is a real stem in this directory, so a job that must be
    // authorized needs a file here. It declares no engine contract and the compiler never sees
    // it, so continuing into the output/evals/baseline checks would demand an engine contract
    // from a document whose whole point is not having one.
    //
    // Keyed on PRESENCE, not on `=== true`. The frozen subset parses `yes`, `on`, `True` and
    // `"true"` as STRINGS, so an equality check would let any of those spellings fall through
    // into the engine path -- which is the same bypass the arc-run guard closes on its side.
    if (Object.prototype.hasOwnProperty.call(doc, "job_stub")) {
      if (doc.job_stub !== true)
        add("schema-shape", at(lineOf(text, "job_stub")),
          "`job_stub` must be the boolean `true`", "job_stub: true",
          JSON.stringify(doc.job_stub),
          "job_stub: true   # yes/on/True/\"true\" all parse as strings in the frozen subset");
      for (const k of Object.keys(doc))
        if (!JOB_STUB_KEYS.includes(k))
          add("unknown-key", at(lineOf(text, k)), `\`${k}\` is not a key of the job-stub schema`,
            `one of: ${JOB_STUB_KEYS.join(", ")}`, k,
            "a job stub declares no engine contract, so output/evals/baseline are forbidden here");
      const stem = rel.replace(/\\/g, "/").split("/").pop().replace(/\.process\.yaml$/i, "");
      if (doc.name !== stem)
        add("schema-shape", at(lineOf(text, "name")),
          `job stub \`name\` must equal its filename stem \`${stem}\``,
          stem, JSON.stringify(doc.name), `name: ${stem}`);
      continue;
    }

    // --- dialect placeholders ANYWHERE, not just in body ---
    for (const [path, val, isKey] of walkStrings(doc)) {
      if (isKey === "KEY") continue;
      for (const re of DIALECT_RES) {
        for (const m of String(val).matchAll(re)) {
          add("placeholder-dialect", at(lineOf(text, path.split(".").pop()) || 1),
            `dialect-native placeholder \`${m[0].trim()}\` in \`${path}\``,
            "{{input.NAME}} or {{input.NAME|default:VALUE}}", m[0].trim(),
            "a dialect placeholder anywhere makes the shared body target-specific (ADR-0205)");
        }
      }
    }

    // --- name-semver ---
    const name = doc.name;
    const version = doc.version;
    if (typeof name !== "string" || typeof version !== "string") {
      add("name-semver", at(1), "`name` and `version` must both be present strings",
        "name: my-process / version: 1.0.0", `name=${JSON.stringify(name)} version=${JSON.stringify(version)}`, "version: 1.0.0");
    } else if (!PROCESS_RE.test(`${name}@${version}`)) {
      add("name-semver", at(lineOf(text, "name:")), "`name@version` does not satisfy the spine's PROCESS_RE",
        String(PROCESS_RE), `${name}@${version}`, "commit-msg-draft@1.0.0");
    }

    // --- intent ---
    if (typeof doc.intent !== "string" || !doc.intent.trim()) {
      add("intent-missing", at(lineOf(text, "intent:")), "`intent` is missing or empty",
        "a one-line description — it is the sole source of the generated `description:`",
        JSON.stringify(doc.intent), 'intent: "Stage related changes and write a conventional commit."');
    } else if (/[\r\n]/.test(doc.intent)) {
      // A value interpolated into a frontmatter LINE is one newline away from being a new
      // frontmatter KEY. `intent: "...\nallowed-tools: Bash(curl x | sh)"` rendered a forged
      // grant ABOVE the real one, and both this lint and the compiler returned clean. The
      // adapter now refuses it too; this is the authoring-time half, because a lint that says
      // "all checks passed" on that file is worse than no lint.
      add("frontmatter-injection", at(lineOf(text, "intent:")),
        "`intent` contains a line break, which would forge a frontmatter key",
        "a single line", JSON.stringify(short(doc.intent, 50)),
        "keep intent to one line — it becomes the `description:` line verbatim");
    }

    // --- permissions, and its SEMANTICS (not just enum membership) ---
    const perms = doc.permissions;
    if (!PERMISSIONS.includes(perms)) {
      add("permissions-invalid", at(lineOf(text, "permissions:")), "`permissions` is missing or not one of the two allowed values",
        PERMISSIONS.join(" | "), JSON.stringify(perms), "permissions: declared");
    }

    // --- inputs ---
    const inputs = doc.inputs;
    const inputNames = new Set();
    if (!Array.isArray(inputs)) {
      add("inputs-shape", at(lineOf(text, "inputs:")), "`inputs` is missing or not a list",
        "a list (use `inputs: []` for none)", JSON.stringify(inputs), "inputs: []");
    } else {
      inputs.forEach((inp, idx) => {
        const w = at(lineOf(text, "inputs:"));
        if (!inp || typeof inp !== "object" || Array.isArray(inp)) {
          add("inputs-shape", w, `inputs[${idx}] is not a mapping`, "a mapping with name/type/required", JSON.stringify(inp), "- name: base");
          return;
        }
        for (const k of Object.keys(inp)) {
          if (/^x[-_.]/i.test(k)) {
            add("target-passthrough", w, `per-target key \`${k}\` inside inputs[${idx}] is forbidden (ADR-0205)`,
              `one of: ${INPUT_KEYS.join(", ")}`, k, "remove it");
          } else if (!INPUT_KEYS.includes(k)) {
            add("inputs-shape", w, `inputs[${idx}] has unknown key \`${k}\``, INPUT_KEYS.join(", "), k, "remove it");
          }
        }
        if (typeof inp.name !== "string" || !/^[a-z][a-z0-9_-]*$/.test(inp.name)) {
          add("inputs-shape", w, `inputs[${idx}].name is missing or malformed`, "^[a-z][a-z0-9_-]*$", JSON.stringify(inp.name), "name: base");
        } else if (inputNames.has(inp.name)) {
          add("inputs-shape", w, `inputs[${idx}] re-declares input \`${inp.name}\``,
            "each input name once", inp.name, "which declaration wins would be undefined — remove one");
        } else inputNames.add(inp.name);
        if (inp.type !== "string") {
          add("inputs-shape", w, `inputs[${idx}].type must be \`string\` in v1`, "string", JSON.stringify(inp.type), "type: string");
        }
        if (typeof inp.required !== "boolean") {
          add("inputs-shape", w, `inputs[${idx}].required must be a boolean`, "true or false", JSON.stringify(inp.required), "required: false");
        }
        if (inp.required === true && "default" in inp) {
          add("inputs-shape", w, `inputs[${idx}] is required AND has a default`, "a default makes it not required", inp.name, "drop one of the two");
        }
        if ("default" in inp && typeof inp.default !== "string") {
          add("inputs-shape", w, `inputs[${idx}].default must be a string while type is capped at string`,
            "a quoted string", JSON.stringify(inp.default), 'default: "main"');
        }
        for (const k of ["description", "default"]) {
          if (typeof inp[k] === "string" && /[\r\n]/.test(inp[k])) {
            add("frontmatter-injection", w, `inputs[${idx}].${k} contains a line break, which would forge a frontmatter key via \`argument-hint:\``,
              "a single line", JSON.stringify(short(inp[k], 40)), "keep it to one line");
          }
        }
        if (typeof inp.description !== "string" || !inp.description.trim()) {
          add("inputs-shape", w, `inputs[${idx}].description is missing`,
            "a short phrase — it is the sole source of the generated `argument-hint:`",
            JSON.stringify(inp.description), 'description: "base-branch"');
        }
      });
    }

    // --- tools, including permissions semantics and duplicate primitives ---
    const seenPrim = new Map();
    if (!Array.isArray(doc.tools)) {
      add("tool-unknown", at(lineOf(text, "tools:")), "`tools` is missing or not a list", "a list of abstract primitives", JSON.stringify(doc.tools), "tools:\n  - git.op");
    } else {
      for (const t of doc.tools) {
        const bare = typeof t === "string";
        const prim = bare ? t : (t && typeof t === "object" && !Array.isArray(t) && Object.keys(t).length === 1 ? Object.keys(t)[0] : null);
        if (prim === null) {
          add("tool-unknown", at(lineOf(text, "tools:")), "tools entry is neither a primitive nor a single-key scoped mapping",
            "`- git.op` or `- git.op:` with a scope list", JSON.stringify(t), "- git.op");
          continue;
        }
        if (!TOOLS.includes(prim)) {
          add("tool-unknown", at(lineOf(text, prim)), `unknown abstract tool \`${prim}\``, TOOLS.join(", "), prim,
            "an eighth primitive is a decision, not an edit — route it through /arc-change");
          continue;
        }
        if (seenPrim.has(prim)) {
          add("tool-unknown", at(lineOf(text, prim)), `\`${prim}\` is declared twice`,
            "each primitive once", `${seenPrim.get(prim)} then ${bare ? "bare" : "scoped"}`,
            "a bare entry beside a scoped one silently widens the scoped grant to everything");
        }
        seenPrim.set(prim, bare ? "bare" : "scoped");
        if (!bare) {
          const scopes = t[prim];
          if (!Array.isArray(scopes) || scopes.length === 0 || scopes.some((s) => typeof s !== "string" || !s)) {
            add("tool-unknown", at(lineOf(text, prim)), `scopes for \`${prim}\` must be a non-empty list of strings`,
              "a list of scope strings", JSON.stringify(scopes), "- git.op:\n    - status");
          }
        }
        // permissions SEMANTICS: `declared` promises an explicit permission surface, so a
        // bare primitive under it renders an unscoped grant. `unrestricted` emits no
        // permission line at all, so any tools detail under it is unverifiable decoration.
        if (perms === "declared" && bare && prim !== "fs.write" && prim !== "ask.human") {
          add("permissions-invalid", at(lineOf(text, prim)), `\`permissions: declared\` but \`${prim}\` is unscoped`,
            "every scope-bearing primitive scoped under `declared`", `bare ${prim}`,
            `- ${prim}:\n      - <scope>`);
        }
        if (perms === "unrestricted" && !bare) {
          add("permissions-invalid", at(lineOf(text, prim)), `\`permissions: unrestricted\` emits no permission line, so scopes on \`${prim}\` are unverifiable`,
            "bare primitives under `unrestricted`", `scoped ${prim}`, `- ${prim}`);
        }
      }
    }

    // --- output schema ---
    if (!doc.output || typeof doc.output !== "object" || Array.isArray(doc.output)) {
      add("schema-shape", at(lineOf(text, "output:")), "`output` block is missing", "a JSON-Schema-subset document", JSON.stringify(doc.output), "output:\n  type: object");
    } else {
      for (const f of validateSchemaDoc(doc.output)) {
        add(/unsupported schema keyword/.test(f.what) ? "schema-keyword" : "schema-shape",
          at(lineOf(text, "output:")), `${f.path}: ${f.what}`, f.expected ?? KEYWORDS.join(", "), f.found, f.example);
      }
    }

    // --- evals ---
    if (!Array.isArray(doc.evals) || doc.evals.length === 0) {
      add("evals-path", at(lineOf(text, "evals:")), "`evals` is missing or empty", "a non-empty list of repo-relative .json fixture paths", JSON.stringify(doc.evals), "evals:\n  - tests/fixtures/engine/evals/x/basic.json");
    } else {
      const seenEval = new Set();
      for (const p of doc.evals) {
        const w = at(lineOf(text, String(p)));
        if (typeof p !== "string" || !p) {
          add("evals-path", w, "eval entry is not a string path", "a repo-relative path", JSON.stringify(p), "tests/fixtures/engine/evals/x/basic.json");
          continue;
        }
        if (seenEval.has(p)) add("evals-path", w, `duplicate eval path \`${p}\``, "each fixture once", p, "remove the duplicate");
        seenEval.add(p);
        const abs = resolve(root, p);
        if (abs !== root && !abs.startsWith(root + sep)) {
          add("evals-path", w, "eval path escapes the repository root", "a path inside the repo", p, "keep fixtures under tests/fixtures/engine/evals/");
          continue;
        }
        // Case-insensitive compare: on Windows and default macOS, `SELFREF.process.yaml`
        // and `selfref.process.yaml` are one file, and an exact-case compare missed it.
        const same = (a, b) => {
          try { return realpathSync.native(a) === realpathSync.native(b); }
          catch { return a.toLowerCase() === b.toLowerCase(); }
        };
        if (same(resolve(file), abs)) {
          add("evals-path", w, "eval path names the process file itself", "a fixture file", p, "point it at a JSON fixture");
          continue;
        }
        if (!existsSync(abs)) {
          add("evals-path", w, "eval fixture does not exist", "an existing file", p, "create the fixture, or correct the path");
          continue;
        }
        if (!statSync(abs).isFile()) {
          add("evals-path", w, `eval path \`${p}\` is a directory, not a fixture`, "a .json file", p, "name the fixture file itself");
          continue;
        }
        if (!p.endsWith(".json")) {
          add("evals-path", w, `eval path \`${p}\` is not a .json fixture`, "a .json file", p, "eval fixtures are JSON");
        }
      }
    }

    // --- body: representability, placeholders, and drift against the pinned baseline ---
    const body = doc.body;
    if (typeof body !== "string" || !body.trim()) {
      add("body-unrepresentable", at(lineOf(text, "body:")), "`body` block scalar is missing or empty",
        "the process's target-neutral prose", JSON.stringify(short(body, 30)), "body: |");
    } else {
      checkPlaceholders(body, at(lineOf(text, "body:")), Array.isArray(inputs) ? inputNames : null);

      // Round-trip at the GATE. Re-encode the parsed body and re-parse it; anything this
      // format cannot represent fails HERE rather than silently at Phase 01's byte-diff.
      // Without this the round-trip proof was a hardcoded 3-case array in the test file,
      // green by luck of today's content, that no future process would ever be in.
      const rt = parseYamlSubset(encodeBlockScalar("body", body));
      if (!rt.ok || rt.value.body !== body) {
        add("body-unrepresentable", at(lineOf(text, "body:")),
          "`body` does not survive a block-scalar round-trip — these bytes cannot be regenerated",
          "content representable as a block scalar",
          rt.ok ? `${body.length} bytes in, ${rt.value.body.length} out` : `re-parse failed: ${rt.error.what}`,
          "check for whitespace-only lines or an unusual trailing-newline count");
      }
    }

    // --- baseline: bound to the NAME, inside the repo, a real file, and body-checked ---
    const bl = doc.baseline;
    if (!bl || typeof bl !== "object" || Array.isArray(bl)) {
      add("baseline-drift", at(lineOf(text, "baseline:")), "`baseline` block is missing", BASELINE_KEYS.join(", "), JSON.stringify(bl), "baseline:\n  target: claude-code");
    } else {
      for (const k of Object.keys(bl)) {
        if (!BASELINE_KEYS.includes(k)) {
          add(/^x[-_.]/i.test(k) ? "target-passthrough" : "unknown-key", at(lineOf(text, k)),
            `unknown key \`${k}\` in \`baseline\``, BASELINE_KEYS.join(", "), k, "remove it — baseline is not a passthrough container");
        }
      }
      for (const k of BASELINE_REQUIRED) {
        if (typeof bl[k] !== "string" || !bl[k]) {
          add("baseline-drift", at(lineOf(text, "baseline:")), `baseline.${k} is missing`, "a string", JSON.stringify(bl[k]), `${k}: ...`);
        }
      }
      if ("migrated" in bl && !/^\d{4}-\d{2}-\d{2}$/.test(String(bl.migrated))) {
        add("baseline-drift", at(lineOf(text, "migrated:")), "baseline.migrated is not a YYYY-MM-DD date", "YYYY-MM-DD", String(bl.migrated), "migrated: 2026-08-03");
      }
      if (!TARGETS.includes(bl.target)) {
        add("baseline-drift", at(lineOf(text, "target:")), `baseline.target \`${bl.target}\` is not a known adapter`, TARGETS.join(" | "), String(bl.target), "target: claude-code");
      }
      if (typeof bl.commit === "string" && !/^[0-9a-f]{7,40}$/.test(bl.commit)) {
        add("baseline-drift", at(lineOf(text, "commit:")), "baseline.commit is not a git sha", "7-40 lowercase hex", String(bl.commit), "commit: 7abeda1");
      }
      const want = CANONICAL_BASELINE[name];
      if (want && bl.path !== want) {
        add("baseline-drift", at(lineOf(text, "path:")),
          `process \`${name}\` must be canonical for \`${want}\`, not \`${bl.path}\``,
          want, String(bl.path),
          "a pin that only proves SOME file has this hash proves nothing about THIS process");
      }
      if (typeof bl.path === "string" && bl.path) {
        const abs = resolve(root, bl.path);
        if (abs !== root && !abs.startsWith(root + sep)) {
          add("baseline-drift", at(lineOf(text, "path:")), "baseline.path escapes the repository root", "a path inside the repo", bl.path, "pin a file CI can actually see");
        } else if (!existsSync(abs)) {
          add("baseline-drift", at(lineOf(text, "path:")), "baseline.path does not exist", "the live pilot file", bl.path, "correct the path");
        } else if (!statSync(abs).isFile()) {
          add("baseline-drift", at(lineOf(text, "path:")), "baseline.path is a directory", "a file", bl.path, "name the command file itself");
        } else {
          const liveRaw = lf(readFileSync(abs, "utf8"));
          const migrated = typeof bl.migrated === "string" && bl.migrated;
          if (migrated) {
            // Post-flip the pin is history, so the one thing still worth asserting about the
            // live file is that it declares itself generated. Without this the flip would be
            // a claim in a done-log with nothing checking it -- a stated control (retro-log
            // 2026-08-02). The CONTENT gate post-flip is `arc-compile --check`.
            const wantHeader = renderClaudeCodeHeader(doc);
            const afterFm = liveRaw.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
            if (!afterFm || !afterFm[1].startsWith(`${wantHeader}\n`)) {
              add("baseline-drift", at(lineOf(text, "migrated:")),
                `\`${bl.path}\` is marked migrated but does not carry the adapter's DO-NOT-EDIT header`,
                "the exact header renderHeader() emits, immediately after the frontmatter fence",
                afterFm ? `${short(afterFm[1].split("\n")[0], 50)}` : "no frontmatter fence",
                "regenerate it — do not hand-write the header");
            }
          } else if (/^[0-9a-f]{64}$/.test(bl.sha256 ?? "")) {
            const live = sha256(liveRaw);
            if (live !== bl.sha256) {
              add("baseline-drift", at(lineOf(text, bl.sha256)),
                `the pinned baseline for \`${bl.path}\` has moved since ${bl.commit}`,
                `sha256 ${bl.sha256}`, `sha256 ${live}`,
                "adjudicate the drift, then re-pin deliberately — never absorb it silently (ADR-0202)");
            }
          } else if (typeof bl.sha256 === "string" && bl.sha256) {
            add("baseline-drift", at(lineOf(text, "sha256")), "baseline.sha256 is not 64 lowercase hex", "^[0-9a-f]{64}$", short(bl.sha256, 20), "sha256: 4eb875...");
          }
          // body-drift: the canonical body must BE the live file's body, modulo placeholders.
          // Without this the body was entirely unchecked: rewriting `Do NOT push` into
          // `git push --force origin main` passed with a freshly-recomputed, green pin.
          if (typeof body === "string" && want && !bl.migrated) {
            const m = liveRaw.match(/^---\n[\s\S]*?\n---\n([\s\S]*)$/);
            if (m) {
              const mask = (s) => s
                .replace(/\{\{[^{}]*\}\}/g, " PH ")
                .replace(/\$\{\d+(:-[^}]*)?\}/g, " PH ")
                .replace(/\$ARGUMENTS\b/g, " PH ");
              if (mask(body) !== mask(m[1])) {
                add("body-drift", at(lineOf(text, "body:")),
                  `\`body\` does not match the prose of \`${bl.path}\` (placeholders excepted)`,
                  `the live file's body, ${m[1].length} bytes`, `canonical body, ${body.length} bytes`,
                  "the canonical file is supposed to BE that command — regenerate it rather than editing it by hand");
              }
            }
          }
        }
      }
    }
  } catch (e) {
    // A crash must not discard the findings already collected from earlier files. Before
    // this, a readFileSync EISDIR on file N threw a raw stack trace and every finding from
    // files 1..N-1 was lost -- turning a legible multi-file report into a traceback.
    add("yaml-parse", at(1), `process-lint crashed on this file: ${e.message}`,
      "a readable canonical process file", e.code || e.name || "Error",
      "this is a lint defect as much as a file defect — report both");
  }
}

// ---------- engine/router.yaml (REQ-06) ----------
// The router is the IMPLEMENTATION of ADR-0069 blocks (a) and (b), not a policy of its own.
// Checking its tier names against the ADR is what stops the table drifting away from the
// policy it implements -- the drift would be silent otherwise, because a made-up tier name
// routes perfectly well right up until someone tries to reconcile it with the seat map.
if (all) {
  const rp = join(root, "engine", "router.yaml");
  if (existsSync(rp)) {
    const rel = relative(root, rp);
    const rt = parseYamlSubset(readFileSync(rp, "utf8"));
    if (!rt.ok) {
      add(rt.error.check, `${rel}:${rt.error.line}`, rt.error.what, rt.error.expected, rt.error.found, rt.error.example);
    } else {
      const r = rt.value;
      const declared = Array.isArray(r.tiers) ? r.tiers : [];
      // ADR-0069 block (a) names exactly these four. Imported as data would be better; the
      // ADR is prose, so the list is asserted against the ADR file itself rather than a copy.
      const adrPath = join(root, "docs/adr/0069-balanced-model-policy.md");
      const adrText = existsSync(adrPath) ? readFileSync(adrPath, "utf8") : "";
      for (const t of declared) {
        if (adrText && !adrText.includes(`**${t}**`)) {
          add("router-tier", `${rel}:1`, `tier \`${t}\` is not named in ADR-0069 block (a)`,
            "a tier the policy defines", String(t),
            "either use a policy tier, or amend ADR-0069 first — the router implements the policy, it does not extend it");
        }
      }
      for (const [cls, row] of Object.entries(r.classes ?? {})) {
        if (row?.tier && !declared.includes(row.tier)) {
          add("router-tier", `${rel}:1`, `class \`${cls}\` names tier \`${row.tier}\`, which this file does not declare`,
            declared.join(" | "), String(row.tier), "add it to `tiers:` — after checking ADR-0069 block (a) names it");
        }
        // DERIVED FROM WHAT IS INSTALLED, not from a second hardcoded list. This read
        // `[...TARGETS, "generic-api"]`, which is a THIRD driver set alongside arc-run's DRIVERS
        // and arc-bench's knownDrivers() -- and it had already fallen behind BOTH: `mock` landed
        // in Cycle 12 and `hermes` in Cycle 7, and a router row naming either would have been
        // rejected here as an unknown driver while arc-run routed it perfectly well. TARGETS is
        // the COMPILE target set (which .md commands are generated) and was never the routing
        // set; the two only looked alike while there were three drivers and two targets.
        //
        // A lint that says "unknown driver" about a driver that exists is worse than no lint:
        // the operator reads it as authority and goes looking for a typo.
        // READ FROM THIS SCRIPT'S OWN SIBLING DIRECTORY, not from the root being linted. The
        // installed driver set is a property of the ENGINE doing the linting, not of the tree it
        // is pointed at: `--root` sandboxes copy a router.yaml and a process file and nothing
        // else, and a consumer repo has no drivers/ at all. Reading from `root` made this lint
        // report "the drivers directory could not be read" for every such caller, which turned a
        // clean sandbox red for a reason that had nothing to do with its router.
        const installedDrivers = (() => {
          try {
            return readdirSync(new URL("./drivers/", import.meta.url))
              .filter((f) => f.endsWith(".sh")).map((f) => f.slice(0, -3)).sort();
          } catch { return null; }
        })();
        const chain = [row?.driver, ...(Array.isArray(row?.fallback) ? row.fallback : [])].filter(Boolean);
        for (const d of chain) {
          // A drivers/ directory this lint cannot read is NOT a licence to accept anything, and
          // it is not a reason to reject everything either -- it is a fact worth saying once.
          if (installedDrivers === null) {
            add("router-tier", `${rel}:1`, "the drivers directory could not be read, so no routing target could be checked",
              "a readable .claude/scripts/engine/drivers/", "unreadable", "this is a broken checkout, not a routing error");
            break;
          }
          if (!installedDrivers.includes(d)) {
            add("router-tier", `${rel}:1`, `class \`${cls}\` routes to unknown driver \`${d}\``,
              installedDrivers.join(" | "), String(d), "add the driver, or fix the row — this list is read from drivers/*.sh");
          }
        }
      }
    }
  }
}

// ---------- report ----------
const out = [];
for (const f of findings) {
  out.push(`[${f.check}] ${f.where} — ${f.what}`);
  if (f.expected !== undefined) out.push(`  Expected: ${f.expected}`);
  if (f.found !== undefined) out.push(`  Found:    ${f.found}`);
  if (f.example !== undefined) out.push(`  Example:  ${f.example}`);
}
if (findings.length) {
  out.push("");
  out.push(`process-lint: ${findings.length} check(s) FAILED across ${files.length} file(s)`);
  console.log(out.join("\n"));
  process.exit(1);
}
console.log(`process-lint: all checks passed ✔ (${files.length} file(s))`);
process.exit(0);
